#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
project_file=${1:-$repo_root/build-mgb64-renderer-device/GoldenPad.xcodeproj/project.pbxproj}
output_file=${2:-$repo_root/docs/source-license-manifest.tsv}

if [ ! -f "$project_file" ]; then
  echo "Missing configured production Xcode project: $project_file" >&2
  exit 1
fi

source_list=$(mktemp "${TMPDIR:-/tmp}/goldenpad-license-sources.XXXXXX")
trap 'rm -f "$source_list"' EXIT

sed -n 's/.*path = \([^;]*\); sourceTree = SOURCE_ROOT.*/\1/p' "$project_file" |
  grep -E '\.(c|cc|cpp|m|mm|swift)$' |
  sed 's#^ref/mgb64/#mgb64/#' |
  LC_ALL=C sort -u > "$source_list"

mkdir -p "$(dirname "$output_file")"
{
  printf '# GoldenPad production source license manifest\n'
  printf '# MGB64 pin: cd9b58f5f91291579b8e551aa925aab000d311cf\n'
  printf '# Generated by scripts/generate-source-license-manifest.sh from the configured game-bearing target.\n'
  printf 'path\torigin\tlicense_boundary\tevidence\n'

  while IFS= read -r source_path; do
    case "$source_path" in
      Sources/*|Support/*)
        origin='GoldenPad project'
        license='GoldenPad-original-no-outbound-license-declared'
        evidence='docs/LEGAL.md'
        ;;
      mgb64/src/platform/fast3d/gfx_pc.c)
        origin='Emill/n64-fast3d-engine derivative'
        license='LicenseRef-n64-fast3d-engine-asset-free-binary'
        evidence='mgb64/src/platform/fast3d/PROVENANCE.md'
        ;;
      mgb64/src/platform/fast3d/gfx_cc.c)
        origin='n64-fast3d-engine and Perfect Dark derivative'
        license='LicenseRef-n64-fast3d-engine-asset-free-binary AND MIT-Perfect-Dark'
        evidence='mgb64/src/platform/fast3d/PROVENANCE.md'
        ;;
      mgb64/src/platform/*|mgb64/src/app/*)
        origin='MGB64 contributors'
        license='MIT-MGB64'
        evidence='mgb64/LICENSE and mgb64/NOTICE.md'
        ;;
      mgb64/src/game/*|mgb64/src/*.c|mgb64/assets/*)
        origin='GoldenEye decompilation via n64decomp/007 and MGB64'
        license='Original-game-rights-no-MGB64-MIT-grant'
        evidence='docs/LEGAL.md and mgb64/THIRD_PARTY.md'
        ;;
      *)
        echo "Unclassified production source: $source_path" >&2
        exit 1
        ;;
    esac
    printf '%s\t%s\t%s\t%s\n' "$source_path" "$origin" "$license" "$evidence"
  done < "$source_list"

  printf '%s\t%s\t%s\t%s\n' \
    'mgb64/lib/cgltf/cgltf.h' \
    'cgltf plus embedded jsmn implementation' \
    'MIT-cgltf-and-jsmn' \
    'mgb64/lib/cgltf/cgltf.h'
  printf '%s\t%s\t%s\t%s\n' \
    'mgb64/lib/stb/stb_image.h' \
    'stb_image implementation' \
    'MIT-or-public-domain-stb' \
    'mgb64/lib/stb/stb_image.h'
} > "$output_file"

echo "Wrote $(($(wc -l < "$output_file") - 4)) source entries: $output_file"
